apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsis-timesheet
  labels:
    app.kubernetes.io/name: vsis-timesheet
    app.kubernetes.io/part-of: vsis-timesheet
automountServiceAccountToken: false
